Fix load error if active_support/core_ext was not loaded before.
ActiveUtils requires some ActiveSupport core extensions in its main file.

Error:
active_utils-2.2.3/lib/active_utils/common/post_data.rb:5:in `<class:PostData>': undefined method `class_attribute' for ActiveMerchant::PostData:Class (NoMethodError)